### ISSUE TITLE
#1 Project base setup

### ISSUE THREAD

**Issue by fego-dev** [Brightcoders-Bootcamps/kata-08-reloj-checador-team03-kata08#1]
# REQUIREMENTS
Creation and management of initial gems of the project

# DESIGN
.-

# Acceptance Criteria
List all required acceptance criteria
.-

**Comment by glorianayeli** [comment]
Done, the base configuration for the project is fine, maybe you can add the test folder for circle ci requirement.

**Comment by LDVera** [comment]
Done, all the initial configurations is good, try to complete the template at the moment of make your issue
